language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install:
- ". ./travis-ci/install-openapi-generator.sh"
- openssl aes-256-cbc -K $encrypted_fad47a4f32eb_key -iv $encrypted_fad47a4f32eb_iv -in ./travis-ci/deploy_keys.tar.enc -out ./travis-ci/deploy_keys.tar -d
- tar xvf ./travis-ci/deploy_keys.tar -C ./travis-ci/
script:
- "/bin/sh ./generate-sdks"
after_success:
- git config --global user.name "Neblio Team"
- git config --global user.email "info@nebl.io"
- "/bin/sh ./travis-ci/push-python-sdk.sh"

